environment: development
name: ffc-mpdp-backend
namespace: ffc-mpdp
workstream: ffc-mpdp
image: ffc-mpdp-backend

labels: {}

appInsights:
  key:

containerConfigMap:
  name: ffc-mpdp-backend-config-map

containerSecret:
  name: ffc-mpdp-backend-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 4
  minReplicas: 1
  maxReplicas: 4
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 0

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 250Mi
  requestCpu: 250m
  limitMemory: 250Mi
  limitCpu: 250m
  port: 3000
  redisHostname: redis-redis-ha.default
  redisPassword: redis
  redisPort: 6379
  redisPartition: ffc-mpdp-backend

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

postgresService:
  postgresDb: ffc_mpdp_backend
  postgresqlHost: ffc-mpdp-backend
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres
