environment: development
name: ffc-mpdp-backend
namespace: ffc-mpdp
workstream: ffc-mpdp
image: ffc-mpdp-backend

labels: {}

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-mpdp-backend-config-map

containerSecret:
  name: ffc-mpdp-backend-container-secret
  type: Opaque

deployment:
  replicas: 3

container:
  requestMemory: 500Mi
  requestCpu: 500m
  limitMemory: 500Mi
  port: 3000
  redisHostname:
  redisPassword:
  redisPort: 6379
  redisPartition: ffc-mpdp-backend

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 30
  failureThreshold: 3
  timeoutSeconds: 10

workloadIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

postgresService:
  postgresDb: ffc_mpdp_backend
  postgresqlHost:
  postgresPort: 5432
  postgresSchema: public
  postgresUser:
