services:
  ffc-mpdp-backend:
    build:
      context: .
      target: production
    image: ffc-mpdp-backend
    container_name: ffc-mpdp-backend
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-mpdp-backend-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      REDIS_HOSTNAME: ffc-mpdp-backend-redis
    depends_on: 
      ffc-mpdp-backend-redis:
        condition: service_started
      ffc-mpdp-backend-postgres:
        condition: service_healthy

  ffc-mpdp-backend-postgres:
    image: postgres:11.4-alpine
    restart: always
    environment:
      POSTGRES_USERNAME: ${POSTGRES_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD:-ppp}
      POSTGRES_DB: ${POSTGRES_DB:-ffc_mpdp_backend}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ffc-mpdp-backend-redis:
    image: redis:4.0.14
