services:
  ffc-mpdp-backend:
    build:
      target: development
    image: ffc-mpdp-backend-development
    container_name: ffc-mpdp-backend-test
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
    environment:
      NODE_ENV: test

  ffc-mpdp-backend-postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
