services:
  ffc-mpdp-backend:
    build:
      context: .
      target: production
    image: ffc-mpdp-backend
    container_name: ffc-mpdp-backend
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-mpdp-backend-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
