services:
  ffc-mpdp-backend:
    build:
      target: development
    image: ffc-mpdp-backend-development
    container_name: ffc-mpdp-backend-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    networks:
      - ffc-mpdp

  ffc-mpdp-backend-postgres:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ffc-mpdp

  ffc-mpdp-backend-redis:
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"
    networks:
      - ffc-mpdp

volumes:
  postgres_data:
  redis_data:

networks:
  ffc-mpdp:
    driver: bridge
    name: ffc-mpdp
