apiVersion: v2
description: description-of-project-goes-here
name: ffc-template-node
# this version is automatically updated in the build pipline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: ^3.1.0
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
