#!/usr/bin/env sh
set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"

docker-compose down
docker-compose -f docker-compose.migrate.yaml down
# Ensure container images are up to date
docker-compose -f docker-compose.migrate.yaml run database-up

docker-compose \
  -f docker-compose.yaml \
  -f docker-compose.override.yaml \
  up $@
